name: Scrape Stamp Prices

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:      # 允許手動觸發

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 獲取完整歷史記錄以便比對
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run scraper
      id: scraper
      run: |
        mkdir -p data
        python scraper.py
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi

    - name: Configure Git
      if: steps.scraper.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push if changed
      if: steps.scraper.outputs.changes == 'true'
      run: |
        git add -A
        git commit -m "更新郵票價格數據 $(date +'%Y-%m-%d')"
        git push
